### PR TITLE
Added "The Shipwrecked Man & The Sea"

### PR DESCRIPTION
**Pull request by daveas**
Hi there!

I found this project on ProductHunt and loved it! I immediately knew I would like to contribute.

I am a sailor so it was easy to choose a theme... Please review at your leisure and let me know if you have any recommendations. (wlo.li/google-type/#dseeman)

### CODE REVIEW

**Comment by daveas** [comment]
Not to be that guy but - any chance these new posts will still be incorporated into your project?

Thanks,
Dave

PS if you need a co-conspirator then I, and/or perhaps another contributor, may be happy to help.

**Comment by adrientetar** [comment]
Needs a rebase.

**Comment by daveas** [comment]
Will do. Many thanks!

**Comment by daveas** [comment]
Thanks for the feedback!

**Pull request closed without merging**
